// The site's words live in src/content/copy/<page>.md (#561, 2026-09-30), so
// Pedro can read and rewrite every line without touching code. This script
// turns them into modules the site imports, and moves the words in and out of
// one whole-site document.
//
//   node scripts/copy.mjs build          compile every page file (runs before dev and build)
//   node scripts/copy.mjs deck [out]     write the whole site as one document (default COPY.md)
//   node scripts/copy.mjs apply <file>   write an edited deck back to the page files
//   node scripts/copy.mjs build --watch  rebuild on every save (live editing, with next dev)
//   node scripts/copy.mjs changes <file> apply the change list copied from the page's review mode
//
// A page file: optional front matter (page, route), then slots. A slot is a
// "## key" heading and the words under it: one paragraph, several paragraphs
// (blank line between), or a list ("- " on every line). Lines starting "> " are
// notes for the writer (budget, what it is, what is locked); they never reach the
// site. "> max 60" sets the slot's budget in characters: the build warns, not
// fails, when a line runs over, because a longer line may still fit.
import { readFileSync, writeFileSync, readdirSync, mkdirSync, rmSync, existsSync, watch } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "src/content/copy");
const OUT = join(ROOT, "src/content/copy.gen");
const KEY = /^[a-z0-9]+([.-][a-z0-9]+)*$/;

function parse(file, text) {
  const errors = [];
  let body = text.replace(/\r\n/g, "\n");
  const meta = {};
  const fm = body.match(/^---\n([\s\S]*?)\n---\n?/);
  if (fm) {
    for (const line of fm[1].split("\n")) {
      const i = line.indexOf(":");
      if (i > 0) meta[line.slice(0, i).trim()] = line.slice(i + 1).trim();
    }
    body = body.slice(fm[0].length);
  }
  const slots = {};
  const parts = body.split(/^## /m);
  // Anything before the first slot is a note for the writer.
  for (const part of parts.slice(1)) {
    const nl = part.indexOf("\n");
    const key = (nl < 0 ? part : part.slice(0, nl)).trim();
    const raw = nl < 0 ? "" : part.slice(nl + 1);
    if (!KEY.test(key)) errors.push(`${file}: "## ${key}" is not a valid slot name (lowercase, digits, dots and hyphens)`);
    if (slots[key]) errors.push(`${file}: slot "${key}" appears twice`);
    const notes = raw.split("\n").filter((l) => /^>\s?/.test(l)).map((l) => l.replace(/^>\s?/, ""));
    const lines = raw.split("\n").filter((l) => !/^>\s?/.test(l));
    const max = Number((notes.join(" ").match(/\bmax (\d+)/) ?? [])[1]) || undefined;
    const filled = lines.filter((l) => l.trim());
    let slot;
    if (filled.length && filled.every((l) => /^\s*- /.test(l))) {
      slot = { t: "list", v: filled.map((l) => l.replace(/^\s*- /, "").trim()) };
    } else {
      const paras = lines.join("\n").split(/\n\s*\n/).map((p) => p.split("\n").map((l) => l.trim()).filter(Boolean).join(" ")).filter(Boolean);
      slot = { t: "text", v: paras };
    }
    if (!slot.v.length) errors.push(`${file}: slot "${key}" is empty`);
    if (max) slot.max = max;
    slots[key] = slot;
  }
  return { meta, slots, errors };
}

function pages() {
  if (!existsSync(SRC)) return [];
  return readdirSync(SRC)
    .filter((f) => f.endsWith(".md") && !f.startsWith("_"))
    .sort()
    .map((f) => ({ file: f, name: f.replace(/\.md$/, ""), text: readFileSync(join(SRC, f), "utf-8") }));
}

function build({ exitOnError = true } = {}) {
  const all = pages();
  const errors = [];
  const warnings = [];
  rmSync(OUT, { recursive: true, force: true });
  mkdirSync(OUT, { recursive: true });
  const names = [];
  let words = 0;
  for (const p of all) {
    const { meta, slots, errors: e } = parse(p.file, p.text);
    errors.push(...e);
    for (const [key, s] of Object.entries(slots)) {
      for (const v of s.v) {
        words += v.split(/\s+/).length;
        if (s.max && v.length > s.max) warnings.push(`${p.file} ${key}: ${v.length} characters, budget ${s.max}: "${v.slice(0, 60)}…"`);
      }
    }
    const mod =
      `// Generated by scripts/copy.mjs from src/content/copy/${p.file}. Edit the .md file, not this.\n` +
      `import type { Page } from "@/content/copy";\n` +
      `const page: Page = ${JSON.stringify({ name: p.name, route: meta.route ?? "", shared: meta.shared ?? "", also: meta.also ?? "", slots }, null, 1)};\n` +
      `export default page;\n`;
    writeFileSync(join(OUT, `${p.name}.ts`), mod);
    names.push(p.name);
  }
  // Every page, for the review mode, which finds each line on the rendered page.
  const id = (n) => "p_" + n.replace(/[^a-z0-9]/g, "_");
  writeFileSync(
    join(OUT, "index.ts"),
    `// Generated by scripts/copy.mjs: every page file, for the review mode.\n` +
      names.map((n) => `import ${id(n)} from "./${n}";`).join("\n") +
      `\nexport const pages = [${names.map(id).join(", ")}];\n`,
  );
  for (const w of warnings) console.warn(`copy: over budget: ${w}`);
  if (errors.length) {
    for (const e of errors) console.error(`copy: ${e}`);
    if (exitOnError) process.exit(1);
    return false;
  }
  console.log(`copy: ${all.length} page files, ${words} words${warnings.length ? `, ${warnings.length} over budget` : ""}`);
  return true;
}

// Live editing: rebuild whenever a page file is saved (Obsidian, an editor),
// so next dev reloads the page. A bad save prints the error and waits for the
// next save; nothing is committed or published.
function watchBuild() {
  build({ exitOnError: false });
  let timer;
  watch(SRC, (_, f) => {
    if (!f || !f.endsWith(".md")) return;
    clearTimeout(timer);
    timer = setTimeout(() => build({ exitOnError: false }), 150);
  });
  console.log(`copy: watching ${SRC}`);
}

// The change list from the page's review mode: blocks of
//   file.md ## slot [item N]
//   was: <old words>
//   now: <new words>
// Each change must find its old words in that slot exactly, or nothing is
// written: a stale list (the file changed since the review) is refused, not
// guessed at.
function changes(file) {
  const text = readFileSync(file, "utf-8").replace(/\r\n/g, "\n");
  const re = /^([a-z0-9.-]+\.md) ## ([a-z0-9.-]+)(?: item (\d+))?\nwas: (.*)\nnow: (.*)$/gm;
  const edits = [...text.matchAll(re)].map((m) => ({ file: m[1], slot: m[2], item: m[3] ? Number(m[3]) : null, was: m[4], now: m[5] }));
  if (!edits.length) {
    console.error("copy: no changes found (expected lines: file.md ## slot / was: ... / now: ...)");
    process.exit(1);
  }
  const touched = new Map();
  for (const e of edits) {
    const path = join(SRC, e.file);
    if (!existsSync(path)) {
      console.error(`copy: ${e.file} is not a page file`);
      process.exit(1);
    }
    const src = touched.get(e.file) ?? readFileSync(path, "utf-8").replace(/\r\n/g, "\n");
    const start = src.search(new RegExp(`^## ${e.slot.replace(/\./g, "\\.")}$`, "m"));
    if (start < 0) {
      console.error(`copy: ${e.file} has no "## ${e.slot}"`);
      process.exit(1);
    }
    const next = src.slice(start + 3).search(/^## /m);
    const end = next < 0 ? src.length : start + 3 + next;
    const section = src.slice(start, end);
    if (!section.includes(e.was)) {
      console.error(`copy: ${e.file} ## ${e.slot} no longer contains "${e.was.slice(0, 60)}"; the file changed since the review. Nothing written.`);
      process.exit(1);
    }
    touched.set(e.file, src.slice(0, start) + section.replace(e.was, e.now) + src.slice(end));
  }
  for (const [f, content] of touched) writeFileSync(join(SRC, f), content);
  console.log(`copy: ${edits.length} change(s) applied to ${touched.size} file(s): ${[...touched.keys()].join(", ")}`);
}

// Site order for the deck: the order a visitor meets the pages.
const ORDER = ["chrome", "home", "work", "case-", "services", "service-", "scorecard", "about", "contact", "security", "privacy", "newsletter", "not-found"];
const rank = (n) => {
  const i = ORDER.findIndex((o) => (o.endsWith("-") ? n.startsWith(o) : n === o));
  return i < 0 ? ORDER.length : i;
};

function deck(out = join(ROOT, "COPY.md")) {
  const all = pages().sort((a, b) => rank(a.name) - rank(b.name) || a.name.localeCompare(b.name));
  const head =
    `# borre.ro: every word on the site\n\n` +
    `> Generated ${new Date().toISOString().slice(0, 10)} from src/content/copy. Edit the words under any "##" heading.\n` +
    `> Keep the "##" headings and the "<!-- file: ... -->" lines as they are: they are how the edits find their way back.\n` +
    `> Lines starting ">" are notes: budgets in characters, and what must not change (figures and their sources).\n` +
    `> Lists stay lists: one "- " line per item.\n\n`;
  const body = all.map((p) => `<!-- file: ${p.file} -->\n${p.text.replace(/\r\n/g, "\n").trim()}\n`).join("\n---\n\n");
  writeFileSync(out, head + body);
  console.log(`copy: wrote ${out} (${all.length} pages)`);
}

function apply(file) {
  const text = readFileSync(file, "utf-8").replace(/\r\n/g, "\n");
  const chunks = text.split(/^<!-- file: (.+?\.md) -->\n/m);
  let changed = 0;
  for (let i = 1; i < chunks.length; i += 2) {
    const name = chunks[i];
    const content = chunks[i + 1].replace(/\n---\n*$/, "").trim() + "\n";
    const target = join(SRC, name);
    if (!existsSync(target)) {
      console.error(`copy: ${name} is not a page file; skipped`);
      continue;
    }
    const { errors } = parse(name, content);
    if (errors.length) {
      for (const e of errors) console.error(`copy: ${e}`);
      process.exit(1);
    }
    if (readFileSync(target, "utf-8").replace(/\r\n/g, "\n") !== content) {
      writeFileSync(target, content);
      changed++;
      console.log(`copy: updated ${name}`);
    }
  }
  console.log(`copy: ${changed} page file(s) changed`);
}

const [cmd, arg] = process.argv.slice(2);
if (cmd === "build" && arg === "--watch") watchBuild();
else if (cmd === "build") build();
else if (cmd === "changes" && arg) changes(arg);
else if (cmd === "deck") deck(arg);
else if (cmd === "apply" && arg) apply(arg);
else {
  console.error("usage: node scripts/copy.mjs build [--watch] | deck [out] | apply <file> | changes <file>");
  process.exit(1);
}
