// The site's words live in src/content/copy/<page>.md (#561, 2026-09-30), so
// Pedro can read and rewrite every line without touching code. This script
// turns them into modules the site imports, and moves the words in and out of
// one whole-site document.
//
//   node scripts/copy.mjs build          compile every page file (runs before dev and build)
//   node scripts/copy.mjs deck [out]     write the whole site as one document (default COPY.md)
//   node scripts/copy.mjs apply <file>   write an edited deck back to the page files
//   node scripts/copy.mjs build --watch  rebuild on every save (live editing, with next dev)
//   node scripts/copy.mjs changes <file> apply the change list copied from the page's review mode
//
// A page file: optional front matter (page, route), then slots. A slot is a
// "## key" heading and the words under it: one paragraph, several paragraphs
// (blank line between), or a list ("- " on every line). Lines starting "> " are
// notes for the writer (budget, what it is, what is locked); they never reach the
// site. "> max 60" sets the slot's budget in characters: the build warns, not
// fails, when a line runs over, because a longer line may still fit.
import { readFileSync, writeFileSync, readdirSync, mkdirSync, rmSync, existsSync, watch } from "node:fs";
import { join, dirname } from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "src/content/copy");
const OUT = join(ROOT, "src/content/copy.gen");
const KEY = /^[a-z0-9]+([.-][a-z0-9]+)*$/;

function parse(file, text) {
  const errors = [];
  let body = text.replace(/\r\n/g, "\n");
  const meta = {};
  const fm = body.match(/^---\n([\s\S]*?)\n---\n?/);
  if (fm) {
    for (const line of fm[1].split("\n")) {
      const i = line.indexOf(":");
      if (i > 0) meta[line.slice(0, i).trim()] = line.slice(i + 1).trim();
    }
    body = body.slice(fm[0].length);
  }
  const slots = {};
  const parts = body.split(/^## /m);
  // Anything before the first slot is a note for the writer.
  for (const part of parts.slice(1)) {
    const nl = part.indexOf("\n");
    const key = (nl < 0 ? part : part.slice(0, nl)).trim();
    const raw = nl < 0 ? "" : part.slice(nl + 1);
    if (!KEY.test(key)) errors.push(`${file}: "## ${key}" is not a valid slot name (lowercase, digits, dots and hyphens)`);
    if (slots[key]) errors.push(`${file}: slot "${key}" appears twice`);
    const notes = raw.split("\n").filter((l) => /^>\s?/.test(l)).map((l) => l.replace(/^>\s?/, ""));
    const lines = raw.split("\n").filter((l) => !/^>\s?/.test(l));
    const max = Number((notes.join(" ").match(/\bmax (\d+)/) ?? [])[1]) || undefined;
    const filled = lines.filter((l) => l.trim());
    let slot;
    if (filled.length && filled.every((l) => /^\s*- /.test(l))) {
      slot = { t: "list", v: filled.map((l) => l.replace(/^\s*- /, "").trim()) };
    } else {
      const paras = lines.join("\n").split(/\n\s*\n/).map((p) => p.split("\n").map((l) => l.trim()).filter(Boolean).join(" ")).filter(Boolean);
      slot = { t: "text", v: paras };
    }
    if (!slot.v.length) errors.push(`${file}: slot "${key}" is empty`);
    if (max) slot.max = max;
    slots[key] = slot;
  }
  return { meta, slots, errors };
}

function pages() {
  if (!existsSync(SRC)) return [];
  return readdirSync(SRC)
    .filter((f) => f.endsWith(".md") && !f.startsWith("_"))
    .sort()
    .map((f) => ({ file: f, name: f.replace(/\.md$/, ""), text: readFileSync(join(SRC, f), "utf-8") }));
}

function build({ exitOnError = true } = {}) {
  const all = pages();
  const errors = [];
  const warnings = [];
  rmSync(OUT, { recursive: true, force: true });
  mkdirSync(OUT, { recursive: true });
  const names = [];
  let words = 0;
  for (const p of all) {
    const { meta, slots, errors: e } = parse(p.file, p.text);
    errors.push(...e);
    for (const [key, s] of Object.entries(slots)) {
      for (const v of s.v) {
        words += v.split(/\s+/).length;
        if (s.max && v.length > s.max) warnings.push(`${p.file} ${key}: ${v.length} characters, budget ${s.max}: "${v.slice(0, 60)}…"`);
      }
    }
    const mod =
      `// Generated by scripts/copy.mjs from src/content/copy/${p.file}. Edit the .md file, not this.\n` +
      `import type { Page } from "@/content/copy";\n` +
      `const page: Page = ${JSON.stringify({ name: p.name, route: meta.route ?? "", shared: meta.shared ?? "", also: meta.also ?? "", slots }, null, 1)};\n` +
      `export default page;\n`;
    writeFileSync(join(OUT, `${p.name}.ts`), mod);
    names.push(p.name);
  }
  // Every page, for the review mode, which finds each line on the rendered page.
  const id = (n) => "p_" + n.replace(/[^a-z0-9]/g, "_");
  writeFileSync(
    join(OUT, "index.ts"),
    `// Generated by scripts/copy.mjs: every page file, for the review mode.\n` +
      names.map((n) => `import ${id(n)} from "./${n}";`).join("\n") +
      `\nexport const pages = [${names.map(id).join(", ")}];\n`,
  );
  for (const w of warnings) console.warn(`copy: over budget: ${w}`);
  if (errors.length) {
    for (const e of errors) console.error(`copy: ${e}`);
    if (exitOnError) process.exit(1);
    return false;
  }
  console.log(`copy: ${all.length} page files, ${words} words${warnings.length ? `, ${warnings.length} over budget` : ""}`);
  return true;
}

// Live editing: rebuild whenever a page file is saved (Obsidian, an editor),
// so next dev reloads the page. A bad save prints the error and waits for the
// next save; nothing is committed or published.
function watchBuild() {
  build({ exitOnError: false });
  let timer;
  watch(SRC, (_, f) => {
    if (!f || !f.endsWith(".md")) return;
    clearTimeout(timer);
    timer = setTimeout(() => build({ exitOnError: false }), 150);
  });
  console.log(`copy: watching ${SRC}`);
}

// The change list from the page's review mode: blocks of
//   file.md ## slot [item N]
//   was: <old words>
//   now: <new words>
// Each change must find its old words in that slot exactly, or nothing is
// written: a stale list (the file changed since the review) is refused, not
// guessed at.
function changes(file) {
  const text = readFileSync(file, "utf-8").replace(/\r\n/g, "\n");
  const re = /^([a-z0-9.-]+\.md) ## ([a-z0-9.-]+)(?: item (\d+))?\nwas: (.*)\nnow: (.*)$/gm;
  const edits = [...text.matchAll(re)].map((m) => ({ file: m[1], slot: m[2], item: m[3] ? Number(m[3]) : null, was: m[4], now: m[5] }));
  if (!edits.length) {
    console.error("copy: no changes found (expected lines: file.md ## slot / was: ... / now: ...)");
    process.exit(1);
  }
  const touched = new Map();
  for (const e of edits) {
    const path = join(SRC, e.file);
    if (!existsSync(path)) {
      console.error(`copy: ${e.file} is not a page file`);
      process.exit(1);
    }
    const src = touched.get(e.file) ?? readFileSync(path, "utf-8").replace(/\r\n/g, "\n");
    const start = src.search(new RegExp(`^## ${e.slot.replace(/\./g, "\\.")}$`, "m"));
    if (start < 0) {
      console.error(`copy: ${e.file} has no "## ${e.slot}"`);
      process.exit(1);
    }
    const next = src.slice(start + 3).search(/^## /m);
    const end = next < 0 ? src.length : start + 3 + next;
    const section = src.slice(start, end);
    if (!section.includes(e.was)) {
      console.error(`copy: ${e.file} ## ${e.slot} no longer contains "${e.was.slice(0, 60)}"; the file changed since the review. Nothing written.`);
      process.exit(1);
    }
    touched.set(e.file, src.slice(0, start) + section.replace(e.was, e.now) + src.slice(end));
  }
  for (const [f, content] of touched) writeFileSync(join(SRC, f), content);
  console.log(`copy: ${edits.length} change(s) applied to ${touched.size} file(s): ${[...touched.keys()].join(", ")}`);
}

// Site order for the deck: the order a visitor meets the pages.
const ORDER = ["chrome", "home", "work", "case-", "services", "service-", "scorecard", "about", "contact", "security", "privacy", "newsletter", "not-found"];
const rank = (n) => {
  const i = ORDER.findIndex((o) => (o.endsWith("-") ? n.startsWith(o) : n === o));
  return i < 0 ? ORDER.length : i;
};

// The deck: every page file in one document, for reading and editing in one
// place (Pedro keeps it in his vault, so it syncs to every device). Each page
// is a "# file.md" heading, its slots the "##" headings under it. The deck
// records the commit it was made from, so `apply` can tell Pedro's edits from
// changes made in the repo since, and never overwrite the latter.
const git = (...args) => execFileSync("git", args, { cwd: ROOT, encoding: "utf-8" }).trim();
const stripFront = (text) => text.replace(/\r\n/g, "\n").replace(/^---\n[\s\S]*?\n---\n?/, "");

function deck(out = join(ROOT, "COPY.md")) {
  if (git("status", "--porcelain", "--", "src/content/copy")) {
    console.error("copy: src/content/copy has uncommitted changes; commit them first, so the deck's base is exact");
    process.exit(1);
  }
  const base = git("rev-parse", "--short=10", "HEAD");
  const all = pages().sort((a, b) => rank(a.name) - rank(b.name) || a.name.localeCompare(b.name));
  const head =
    `# borre.ro copy\n\n` +
    `> Every word on the site, page by page. Change the words under any "##" heading; lines starting ">" are notes (where the words show, and a budget in characters).\n` +
    `> Keep the "#" and "##" headings as they are, and keep lists as lists ("- " per line). Figures and prices are in the site's code, not here.\n` +
    `> When you're done, tell Claude "apply the copy note". Only the lines you changed are applied, on the copy branch, and nothing goes live until you approve the preview.\n` +
    `> Base: ${base} (${new Date().toISOString().slice(0, 10)}). Leave this line as it is.\n\n`;
  const body = all
    .map((p) => {
      const page = (p.text.match(/^page:\s*(.+)$/m) ?? [])[1];
      return `# ${p.file}${page ? ` · ${page}` : ""}\n\n${stripFront(p.text).trim()}\n`;
    })
    .join("\n");
  writeFileSync(out, head + body);
  console.log(`copy: wrote ${out} (${all.length} pages, base ${base})`);
}

// Slot bodies by file, from a deck or a page file: { "home.md": { "hero.summary": ["line", ...] } }.
function deckSlots(text) {
  const files = {};
  const parts = text.replace(/\r\n/g, "\n").split(/^# ([a-z0-9-]+\.md)\b.*$/m);
  for (let i = 1; i < parts.length; i += 2) files[parts[i]] = bodies(parts[i + 1]);
  return files;
}
function bodies(text) {
  const out = {};
  const parts = stripFront(text).split(/^## /m);
  for (const part of parts.slice(1)) {
    const nl = part.indexOf("\n");
    const key = (nl < 0 ? part : part.slice(0, nl)).trim();
    const lines = (nl < 0 ? "" : part.slice(nl + 1)).split("\n").filter((l) => !/^>\s?/.test(l));
    while (lines.length && !lines[0].trim()) lines.shift();
    while (lines.length && !lines[lines.length - 1].trim()) lines.pop();
    out[key] = lines.map((l) => l.trimEnd());
  }
  return out;
}
const same = (a, b) => JSON.stringify(a) === JSON.stringify(b);

// Applies a deck: three-way, slot by slot. For each slot the deck changed
// since its base commit, the page file must still hold the base words;
// otherwise it is a conflict and nothing is written. Notes are never changed.
function apply(file) {
  const text = readFileSync(file, "utf-8");
  const base = (text.match(/^> Base: ([0-9a-f]{7,40})\b/m) ?? [])[1];
  if (!base) {
    console.error('copy: the deck has no "> Base:" line, so its edits can\'t be told apart from newer changes; ask for a fresh deck');
    process.exit(1);
  }
  const edited = deckSlots(text);
  const edits = [];
  const conflicts = [];
  for (const [name, slots] of Object.entries(edited)) {
    const target = join(SRC, name);
    if (!existsSync(target)) {
      console.error(`copy: ${name} is not a page file; skipped`);
      continue;
    }
    let baseText;
    try {
      baseText = git("show", `${base}:src/content/copy/${name}`);
    } catch {
      console.error(`copy: ${name} isn't in the base commit ${base}; skipped`);
      continue;
    }
    const was = bodies(baseText);
    const now = bodies(readFileSync(target, "utf-8"));
    for (const [key, lines] of Object.entries(slots)) {
      if (!(key in was)) {
        console.error(`copy: ${name} "## ${key}" is new or renamed; slots are added in code, so it was skipped`);
        continue;
      }
      if (same(lines, was[key])) continue; // not edited in the deck
      if (!(key in now)) conflicts.push(`${name} ## ${key}: the slot no longer exists`);
      else if (same(now[key], lines)) continue; // already applied
      else if (!same(now[key], was[key])) conflicts.push(`${name} ## ${key}: changed in the repo since the deck was made`);
      else edits.push({ name, key, lines });
    }
  }
  if (conflicts.length) {
    for (const c of conflicts) console.error(`copy: conflict: ${c}`);
    console.error("copy: nothing written. Ask for a fresh deck, or say which version to keep.");
    process.exit(1);
  }
  const touched = new Map();
  for (const e of edits) {
    const target = join(SRC, e.name);
    const src = touched.get(e.name) ?? readFileSync(target, "utf-8").replace(/\r\n/g, "\n");
    const start = src.search(new RegExp(`^## ${e.key.replace(/\./g, "\\.")}$`, "m"));
    const next = src.slice(start + 3).search(/^## /m);
    const end = next < 0 ? src.length : start + 3 + next;
    const section = src.slice(start, end).split("\n");
    const notes = section.slice(1).filter((l) => /^>\s?/.test(l));
    const rebuilt = [section[0], ...notes, ...e.lines].join("\n") + (next < 0 ? "\n" : "\n\n");
    touched.set(e.name, src.slice(0, start) + rebuilt + src.slice(end));
  }
  for (const [name, content] of touched) {
    const { errors } = parse(name, content);
    if (errors.length) {
      for (const err of errors) console.error(`copy: ${err}`);
      console.error("copy: nothing written.");
      process.exit(1);
    }
  }
  for (const [name, content] of touched) writeFileSync(join(SRC, name), content);
  for (const e of edits) console.log(`copy: applied ${e.name} ## ${e.key}`);
  console.log(`copy: ${edits.length} slot(s) changed in ${touched.size} file(s)`);
}

const [cmd, arg] = process.argv.slice(2);
if (cmd === "build" && arg === "--watch") watchBuild();
else if (cmd === "build") build();
else if (cmd === "changes" && arg) changes(arg);
else if (cmd === "deck") deck(arg);
else if (cmd === "apply" && arg) apply(arg);
else {
  console.error("usage: node scripts/copy.mjs build [--watch] | deck [out] | apply <file> | changes <file>");
  process.exit(1);
}
